export type TicketAnalysis = {
  id: string;
  ticket_id: string;
  provider: string;
  agent_version: string;
  summary: string;
  category?: string | null;
  subcategory?: string | null;
  product?: string | null;
  module?: string | null;
  version?: string | null;
  device?: string | null;
  operating_system?: string | null;
  error_message?: string | null;
  impact?: string | null;
  affected_users: number;
  store_stopped: boolean;
  fiscal_risk: boolean;
  data_loss_risk: boolean;
  priority: string;
  confidence: number;
  missing_information: string[];
  suggested_questions: string[];
  possible_causes: string[];
  recommended_actions: string[];
  knowledge_sources: Array<Record<string, unknown>>;
  triggered_rules: string[];
  requires_human: boolean;
  requires_authorization: boolean;
  safety_notes: string[];
  created_at: string;
  updated_at: string;
};
