from enum import StrEnum


class IntentType(StrEnum):
    INCIDENT = "INCIDENT"
    HUMAN_REQUEST = "HUMAN_REQUEST"
    STATUS_REQUEST = "STATUS_REQUEST"
    CANCEL_REQUEST = "CANCEL_REQUEST"
    RESTART_REQUEST = "RESTART_REQUEST"
    GREETING = "GREETING"
    CONFIRMATION = "CONFIRMATION"
    DENIAL = "DENIAL"
    INFORMATION = "INFORMATION"
    UNKNOWN = "UNKNOWN"


class IncidentCategory(StrEnum):
    PDV_STARTUP = "PDV_STARTUP"
    DATABASE = "DATABASE"
    NETWORK = "NETWORK"
    SERVER = "SERVER"
    FISCAL = "FISCAL"
    PRINTER = "PRINTER"
    TEF = "TEF"
    PAYMENT = "PAYMENT"
    INVENTORY = "INVENTORY"
    PRODUCT_REGISTRATION = "PRODUCT_REGISTRATION"
    SALES = "SALES"
    CASH_REGISTER = "CASH_REGISTER"
    BACKUP = "BACKUP"
    UPDATE = "UPDATE"
    AUTHENTICATION = "AUTHENTICATION"
    PERMISSION = "PERMISSION"
    WINDOWS = "WINDOWS"
    PERFORMANCE = "PERFORMANCE"
    INTEGRATION = "INTEGRATION"
    HARDWARE = "HARDWARE"
    UNKNOWN = "UNKNOWN"


class SeverityLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class ClassifierSource(StrEnum):
    RULE = "RULE"
    FALLBACK = "FALLBACK"
